cmd/scepclient/csr.go
cmd/scepclient/scepclient.go
cmd/scepserver/scepserver.go
server/depot.go
server/service.go

Please review and merge this 
- adding a server flag to allow renewals of certificates only n days before expiry
- add functionality to server to revoke certificates in the cadb if a renewal is allowed
Minor fixes :
- verify if ou,location,state, org and country are actually set in a CSR, remove from the CN if not
- minor code cleanup

Add allowRenewal flag, add revocation functionality

---

cmd/scepclient/csr.go
cmd/scepclient/scepclient.go
cmd/scepserver/scepserver.go
server/depot.go
server/service.go

gofmt code

---

server/depot.go

if there was no index.txt file, the server would error.

create index.txt file if missing

---

cmd/scepserver/scepserver.go
depot/bolt/depot.go
depot/bolt/depot_test.go

create BoltDB depot implementation

---

depot/bolt/depot.go
depot/bolt/depot_test.go
server/service.go

Add methods to create a new private key and CA.

depot/bolt: add CA and Key init methods

---

depot/file/depot.go

This should address the concerns from #9

Added an if block to fix CA passwords when undefined

---

challenge/bolt/challenge.go
challenge/challenge.go
server/service.go
server/service_bolt_test.go

WIP branch to add support for unique challenge passwords
For #4

support dynamic challenge passwords

---

cmd/scepclient/csr.go
cmd/scepclient/scepclient.go
glide.lock
glide.yaml
scep/scep.go
server/service.go

support AES encryption and SHA-256, defaulting to SHA256 and AES if the server supports them

support SCEPStandard

---

scep/scep.go
server/service.go

use failInfo badMessage for bad challenge password

---

client/client.go
cmd/scepclient/scepclient.go
cmd/scepserver/scepserver.go
scep/scep.go
server/endpoint.go
server/service.go

Adds JSON log output and debug logging to scep operations.

improve logging options

---

server/transport_test.go

cleans up files created by the FileDepot while running tests.

cleanup files after running tests

---

server/service.go

Copy DNS and IP information from CSR.

copy more alternative names

---

.github/workflows/CI.yml

This PR adds a very basic continuous integration action that makes sure that all go files build successfully and that all tests pass successfully.

Add continous integration action

---

depot/signer.go

PR #121 was wiped out by the merge of #113 I think. Re-applying the changes to the new location of the certificate template here.

Re-do of PR #121

---

.github/workflows/CI.yml

This PR adds a check for the code format in the CI github action.

Add gofmt to CI

---

depot/bolt/depot.go

Fixes another place we're passing raw bolt `.Get()` data to `x509.ParseCertificate` (which retains a reference). Per the Bolt manual:
> Please note that values returned from Get() are only valid while the transaction is open. If you need to use a value outside of the transaction then you must use copy() to copy it to another byte slice.

Bolt memory reference copy

---

Dockerfile

Baking in CA init was a mistake. Revert.

Revert Dockerfile ENTRYPOINT change

---

server/transport_test.go

This PR removes unused test functions.

Remove unused test functions

---

depot/file/depot.go

Use alternate certificate filename if CN is missing in file Depot

---

Makefile

The new target has been tested on Raspberry Pi 4B

Update Makefilewith linux-arm targets

---

README.md

Updates the instructions getting rid of go commands.

Update the compilation instruction in README.md

---

Makefile
README.md
cmd/scepserver/scepserver.go

Added common name (CN) to CA certificate, which can also be set on the command line, when the server is initialized.

Added common name to CA cert.
