cmd/scepclient/scepclient.go

Guard against no certificates being provided (or possibly incorrectly parsed) in the PKCS7 degenerate from SCEP GetCACert message.

Check for no certificates and error

---

cmd/scepserver/scepserver.go
server/depot.go
server/service.go

The patch allows us to :
* generate a CA outside of micromdm
* this allows us to use openssl directly creating the CA
* this allows us to use all the nasty OpenSSL features (such as extensions/crls/oscp etc :)
* add the functionality to pass the CA private key password on startup of the server
* add the funcitonality to keep track of all issued certificates in the CA Database (see http://pki-tutorial.readthedocs.io/en/latest/cadb.html)
* This allows us to revoke certificates later
* switch the serial file format from binary to text

add CA Database, switch serial file to text, add CA-Private Key parameter

---

depot/file/depot.go
server/service.go
server/transport.go

This PR undoes the commit e93b212; Fix issues #23 and #24.

Fix various bugs

---

depot/bolt/depot.go
server/service_bolt_test.go
server/transport_test.go

The original `[]byte` must not be referenced after the transaction is closed, but asn.Unmarshal stores it in the certificate when calling
the x509.ParseCertificate method.

create a copy of the raw cert byteslice before calling ParseCertificate

---

cmd/scepclient/scepclient.go
scep/scep.go
server/transport.go
server/transport_test.go

Refactoring a bunch of related bugs to make scpeclient work with windows.

Support NDES with scepclient

---

cmd/scepclient/csr.go
crypto/x509util/doc.go
crypto/x509util/x509util.go
crypto/x509util/x509util_test.go
scep/scep.go

x509util.CreateCertificateRequest wraps x509.CreateCertificateRequest and adds
support for challengePassword attribute.
Adding a new attribute means re-signing the whole CSR, which means importing
private methods and types from the x509 package.  I hope to eventually submit a CL to the stdlib.
Go Issue: https://github.com/golang/go/issues/15995

add x509util package

---

client/scep.go
cmd/scepclient/scepclient.go
server/endpoint.go
server/transport.go

made a few small changes to HTTP transport:
1)
Use the request/response struct instead of ctx for passing values around.
Closes #41
2)
Added an io.LimitReader when reading request/response payloads.
The payload limit is 2MB.
3)
Added an Endpoint logging middleware and updated the client and server to use it.

clean up http transport

---

server/transport.go

tries to read the response body instead of the mistakenly added io.LimitReader

add response body to error

---

depot/file/depot.go

Makes index.txt compatible with openssl.
After trying to generate a CRL with openssl, I noticed that openssl expects the serial numbers to have a leading 0 if the number of digits is not even.

Fixes the cert serial formatting in index.txt

---

Gopkg.toml

Get the pkcs7 package via https, not ssh

Allow build without github ssh keys

---

cmd/scepserver/scepserver.go

With this patch, the ca certificate and key can be used to sign a CRL.

Add CRL signing key usage to CA

---

Dockerfile
README.md

I found that the existing Dockerfile downloaded a release version and installed it in the image. I don't really see how that approach is usable other than for generating an image based on a specific release version of the SCEP server. In any case, the user should be able to download a specific version directly from Docker hub instead. 
With the Dockerfile in this pull request, the image is built using the compiled version of SCEP server/client.
The entrypoint is set to start the server, but the user can just override it on container start to start the scep client instead.

Build docker image from current build, not static version

---

depot/bolt/depot.go
scep/testdata/testca/sceptest.mobileconfig

Fixes https://github.com/micromdm/micromdm/issues/381
Questions around #381 come up a lot in #micromdm chat on Mac Admins slack. I think a long term solution can be done as requested [here](https://github.com/micromdm/micromdm/issues/278) and either allow the user to set more from the command line or just let users do something like upload their own CA cert to be used.
I think it's worth making this small change so when users test out MicroMDM for the first time they don't think there's something wrong during enrollment.

Set a default CommonName on new CA certs

---

cmd/scepserver/scepserver.go

Format for logger.Log() params is pairs of name and attribute.
Without this change, the program dies with no output.
Verify by starting the server with an invalid argument to -csrverifierexec

Fix these error logs

---

depot/file/depot.go

the Atoi method to convert the date does not work on 32 bits architectures. I propose to replace this with ParseInt as it seems to work both on 32 and 64 bits architectures.

changed date conversion method for 32 bits architecture

---

scep/scep.go

This is required for Mikrotik RouterOS clients - fixes #80.

Include senderNonce attribute in CertRep message

---

server/service.go

This allows generating certificates that can be used for purposes such as VPN authentication, where it might be desirable to identify the user by their email address.

Copy email addresses from CSR SANs to the X509 template

---

scep/scep.go

Improves logging. Aided in debugging a bad CSR.

Wrap error when parsing CSR

---

server/transport.go
server/transport_test.go

This patch add decoding of base64-encoded messages in PKIOperation queries.
Tested against juniper (junos 20.1) client and found working. Juniper behaviour slightly
differs from already proposed idea:
a) it does not encodes all messages with base64, only PKIOperation. For example, 
with GetCACert query looks like  path="/scep?operation=GetCACert&message=CA-CERT-NAME"
(not encoded), and attempt to decode such string will lead to decoding failure (may be
GetCACert is not considered as binary, and only binary data shall be encoded per rfc).
b) before decoding, messages are unescaped.

Decode binary in GET requests. Closes #98.

---

scep/scep.go

We are experimenting with SCEP, and we had to do this modification to allow CSR with EC keys. This PR is far from ideal. There are [three](https://github.com/micromdm/scep/blob/e9687bac0bd7c9ad3d508b070308a9dacefb8f47/depot/bolt/depot.go#L321) [other](https://github.com/micromdm/scep/blob/a136542b4bc9312ba88f1beaf1369d67bc744614/cmd/scepserver/scepserver.go#L318) [places](https://github.com/micromdm/scep/blob/e9687bac0bd7c9ad3d508b070308a9dacefb8f47/server/service.go#L297) where the same function is implemented in this repository. It would probably need some extra patching too, or a refactoring. This is more to start a conversation.

Accept ECDSA keys in the scep core module

---

cmd/scepclient/scepclient.go

This PR removes the field sigAlgo which was removed from csrOptions as a result of PR #116.
With this PR, running `go build ./...` works successfully.

Remove unknown field sigAlgo

---

server/service_bolt_test.go

This PR fixes TestCaCert function so that it passes.
The main problem was that CA private key was used instead of the signer (SCEP signer) key to sign CSRs.

Fix TestCaCert in service_bolt_test.go

---

go.mod
go.sum

This PR is to use github.com/omorsi/pkcs7 fork (particularly till this [commit](https://github.com/omorsi/pkcs7/commit/a7b80a2a856844170346f1189008367c9251279e)) instead of the go.mozilla.org/pkcs7 fork.
To see the differences between both repos, please check [diffs](https://github.com/mozilla-services/pkcs7/compare/master...omorsi:master).
The change introduced by github.com/omorsi/pkcs7 is necessary for `go build ./...` and `go test ./...` commands to succeed for micromdm/scep.

Use github.com/omorsi/pkcs7 instead of go.mozilla.org/pkcs7

---

Makefile
challenge/challenge.go
challenge/challenge_bolt_test.go
cmd/scepserver/scepserver.go
csrverifier/csrverifier.go
depot/signer.go
scep/scep.go
scep/scep_test.go
server/service.go
server/service_bolt_test.go
server/transport_test.go

*tl;dr* Changes internal API for how signing of certificates works in the scep server.
This PR changes the core organization of the SCEP server service in support of #112. The service itself (in `server/service.go`) is much simplified due to removing all CA functionality. In lieu of CA implementation details being in the server service we opted for a way to modularlize certificate signing (and any other duties that need to inspect and take action on the CSR). Thus the `scepserver.CSRSigner` interface:
```go
// CSRSigner is a handler for CSR signing by the CA/RA
//
// SignCSR should take the CSR in the CSRReqMessage and return a
// Certificate signed by the CA.
type CSRSigner interface {
SignCSR(*scep.CSRReqMessage) (*x509.Certificate, error)
}
```
Due to the interface and associated …

Pluggable CSR signing framework

---

README.md

Currently this just links to the .SVG file.

Link CI badge to build history

---

.github/workflows/CI.yml

Current setup only runs build tests on new commits to master and new pull requests (based on `master`). This removes the `master` branch requirement from PRs and reruns builds on each new commit to PRs.

Run CI on new commits to pull requests

---

depot/bolt/depot.go
scep/scep.go
scep/scep_test.go

This PR is to solve issue #123.
Copying the issue description here to save readers' time.
------
Currently, the CSR sent in a PKCSReq message is encrypted with all the certificates returned from GetCaCert operation.
https://github.com/micromdm/scep/blob/f3adbb75202bf4f4f244e05be4f315f708bb75b0/scep/scep.go#L448
A windows SCEP server may not just return the CA certificate, but also NDES certificates. Some of these certificates are not created with KeyEncipherment KeyUsage. Some of them are only for Digital Signature purposes. Adding these certificates as recipients for the encrypted messages introduces decryption errors from the server's side.
The proposal here is to filter the certificates received from GetCaCert by KeyUsage, particularly KeyEncipherment, and use only those as the …

Encode CSRs only with certificates with KeyEncipherment KeyUsage

---

scep/certs_selector.go
scep/certs_selector_test.go
scep/scep.go
scep/scep_test.go

As mentioned in #145, some CAs don't have `KeyUsageKeyEncipherment` key usage set in their certificates. This PR introduces `CertsSelector` which should make it easier for clients that want to enforce a custom criteria on how to filter certificates.

Add CertsSelector option

---

cmd/scepclient/csr.go
cryptoutil/x509util/x509util.go

This PR solves issue #143 and also removes insecure MD2 and MD5 hashing algorithms.
Copying the issue description here to save readers' time.
------
Since SHA-1 is insecure [(attacks)](https://en.wikipedia.org/wiki/SHA-1#Attacks), this issue is to propose to stop supporting clients using it to sign CSRs.
SHA-1 can be used to sign CSRs using micromdm/scep in the following cases:
- The scepclient default behavior is to sign CSRs using SHA1WithRSA. (This can be changed to SHA256WithRSA) https://github.com/micromdm/scep/blob/1078401fb42b520d9a0fb35d6f78ec46a62c5f7b/cmd/scepclient/csr.go#L46
- Also signers can use SHA-1 if a challenge need to be added (This can be changed by removing SHA-1 support from x509util) https://github.com/micromdm/scep/blob/1078401fb42b520d9a0fb35d6f78ec46a62c5f7b/cryp …

Stop supporting SHA-1 for signing CSRs

---

server/transport.go

[SCEP-23 Appendix-F](https://tools.ietf.org/html/draft-nourse-scep-23#appendix-F) omits the inclusion of a Content-Type. However I know of at least one commercial SCEP server that depends on using a Content-Type and I believe Apple SCEP clients also set a Content-Type header. Open to discussion, of course.

Use Content-Type: application/octet-stream for POST PKIOperation

---

challenge/challenge.go
challenge/challenge_bolt_test.go
cmd/scepserver/scepserver.go
csrverifier/csrverifier.go
server/csrsigner.go
server/csrsigner_test.go
server/service.go

- Move `CSRSigner` and pals to new file.
- Add a test for the (static) challenge verifier.
- Change challenge verifier to use `subtle.ConstantTimeCompare()` rather than string compare.
- Rename most `Middleware` adapters. Their containing package gives them context.
- Remove the `.WithCSRSignerMiddleware()` adapter/middleware as a `ServiceOption`. Too verbose and abstracted. Instead just wrap the `CSRSigner`s directly.
- Error consistency.
- Create `NopCSRSigner()` (for testing).
- Sort imports: stdlib, project, external.

CSRSigner cleanup

---

cmd/scepserver/scepserver.go
depot/signer.go
server/service_bolt_test.go

Depot signer was just a `CSRSignerFunc`. Which worked but its flexibility was limited. Turn it into a real Go struct with associated Options. My hope is that this makes it easier for folks to integrate things like additional attributes for issues like #103 and #91.

Create Depot signer struct with Options

---

cmd/scepclient/scepclient.go
server/endpoint.go
server/service.go
server/service_bolt_test.go
server/service_logging.go
server/transport.go
server/transport_test.go

[SCEP-23 § 5.2.1](https://tools.ietf.org/html/draft-nourse-scep-23#section-5.2.1) **GetCACert** says
> The MESSAGE MAY be omitted, or it MAY be a string that represents the certification authority issuer identifier.  A CA Administrator defined string allows for multiple CAs supported by one SCEP server.
Allow passing this through to a SCEP server. Our server doesn't do anything with it at the moment, but support its use on the client-side.

Support message with GetCACert call

---

README.md
cmd/scepclient/scepclient.go

This PR solves issue #156.
Copying the issue description here to save readers' time.
------
This is to complete pull request #144 which should have removed all weak hash functions usages.
https://github.com/micromdm/scep/blob/c89253406d2e73be69933382e1c0aed9069283be/cmd/scepclient/scepclient.go#L271

Expect SHA-256 instead of MD5 fingerprint flag value

---

cmd/scepclient/scepclient.go

Threw this together in support of #156. It looks like this when logged:
```
ts=2021-03-19T23:30:47.620605Z level=info msg=dumpca idx=0 rdns="OU=SCEP CA,O=scep-ca,C=US" sha256=7b659515f1f2a9c1af5c32e51fcdbeb67adfd4679d7998d0f29c757316cd29b7
```

Debug log CA certs and hashes in scepclient

---

cmd/scepclient/scepclient.go

Looking at your diff again @omorsi in #160 I thought about using the `CertsSelector` interface as passed through the `cfg` object. What do you think? I also made the fingerprint certsselector return a single cert.
Incidentally I _just saw_ that you submitted #162 which also addresses that last bit, lol.

Use CertsSelector to get cert matching (SHA2) fingerprint

---

README.md
cmd/scepclient/scepclient.go

Since we're changing the fingerprint hash lets be extra sure that folks are inputting a correct SHA-256 fingerprint. We don't want folks assuming they can just use an md5 or sha1 and it'll work.

Validate input SHA-256 fingerprint

---

cmd/scepclient/scepclient.go
scep/certs_selector.go
scep/scep.go

Since we're now (potentially) filtering certificates with `scep.CertsSelector`s (#147) and the new option to add additional CAs `scep.WithCACerts()` (#131) it would be nice to pull out the filtered set of certificates from the created `PKIMessage`. Luckily we just need to populate it in the existing struct that's already returned. This allows us to just reference it for the (likely) shortly-following `ParsePKIMessage` message call.
WDYT @omorsi?

CSR recipients refactor

---

cmd/scepserver/scepserver.go
depot/bolt/depot.go
depot/cacert.go
scep/scep_test.go

Move the CA cert generating into the `depot` package. This de-dups the two places where this was happening and sets us up to potentially move all CA-related operations into the `depot` package and/or depot implementations.

Refactor CA cert generation

---

Makefile

This is rather cosmetic PR.
Adds ability to build client/server binaries to be used with MacBooks running Apple M1 chip.

added Apple M1 specific release target

---

depot/signer.go

This addresses the data race problems mentioned #184 by protecting the depot in SignCSR with a mutex. Currently if SignCSR gets overloaded it can break the whole depot by not correctly incrementing the serial (multiple concurrent requests can get the same serial), or checking the CN database can be inconsistent (multiple concurrent requests can cause errors because of concurrent file access or possibly return bad data).
It might be that mutexes could be added to the depot itself, but this could get much more complex without getting many (or any) speed gains. `SignCSR` calls `depot.Serial` near the top, then calls `depot.Put` at the bottom which internally calls `depot.Serial`, and both `depot.Serial` calls should return the same serial, so the serial should be locked for the length of …

Fix data races in SignCSR

---

depot/signer.go

Got an error in some enrollment cases, where the device's time was slightly off of the server's time (about 10 seconds)
It seems like when issuing a certificate, it was intentionally subtracting time in the `NotBefore` field for to allow these minor discrepancies.
The problem is that it was adding -600 **nanoseconds** which is not nearly enough for such cases, and I think was a mistake as it seems the intention was to add -600 **seconds**
Hope I'm right :)

Increase Signer grace from 600ns to 10 minutes

---

cmd/scepserver/scepserver.go

This adds a command line option/environment variable to control the bind address. Previously it was always left blank, causing the server to listen on all addresses. This is still the default behavior. The primary use-case I see for this is for when a user wants the server to only be accessible from localhost (so bind to 127.0.0.1). Another possible use-case would be when a server has both publicly accessible interfaces and internal interfaces, though I expect this configuration is uncommon.

make bind address configurable

---

cmd/scepserver/scepserver.go
depot/signer.go

Create a server option and CLI switch to add key usages to the certificate for server-type certificates.

Sign cert with key usages for server authentication.

---

depot/signer.go
server/service_bolt_test.go

[x] Summary
While creating the x509 template for signing certificates, the depot signer specifies the signing algorithm as picked from the x509 CSR. This assumption is incorrect because the CA key type will not always match the requestor's key type.  In addition, the signing algorithm in the CSR is for generally for the verifier to know what algorithm is to be used to verify the CSR signature. While the algorithm to be used to sign the actual certificate is more of a CA/Signer property.
This PR retains the existing behavior but allows overrides for consumers of the depot library.
[x] Test
```
[scep]$ make test
go test -cover ./...
?   	github.com/micromdm/scep/v2/challenge/bolt	[no test files]
?   	github.com/micromdm/scep/v2/client	[no test files]
ok …
```

Allowing specifying signing algorithm for depot signer

---

depot/bolt/depot.go
depot/bolt/depot_test.go
depot/file/depot.go
depot/signer.go

Changes a few things to make serial number generation make a bit more sense. This brings the implementation in line with the following statements:
> `Depot.Serial()` should always generate a unique new serial number. It's up to `Depot.Put()` to use the serial number in the generated certificate for storage, minding that there may very well be sequence gaps.
To that end adjust a bunch of things to make it conform to this. Add a mutex in case `Serial()` is called multiple times concurrently. Fix a few other unrelated things along the way. See also #185 for more context.

BoltDB Depot serial number changes for data races
